name: Develop workflow

on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run security scan
        run: echo "Running security scan..."
  build:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          docker build -t my-app:latest .
